# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

[gcloud]
disabled = true

[docker_context]
disabled = true

[git_branch]
symbol = "🌱 "
style = "bold cyan"
truncation_length = 20

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = "🏳"
deleted = "✘"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
modified = "!"
renamed = "»"
staged = "[+](green)"
stashed = "📦"  # Use a symbol instead of $
untracked = "?"
style = "bold red"
